FROM armhf/ubuntu:14.04
RUN apt-get update && \
     apt-get install --no-install-recommends -y \
     arptables \
     bridge-utils \
     ca-certificates \
     curl \
     iptables \
     libssl-dev \
     libffi-dev \
     gcc \
     make \
     conntrack \
     libaio1 \
     fio && \
     jq && \
    curl -s https://www.python.org/ftp/python/2.7.11/Python-2.7.11.tgz | tar -zxv -C /tmp/ && \
    cd /tmp/Python-2.7.11 && ./configure && make && make install && \
    curl -s https://bootstrap.pypa.io/get-pip.py | python && \
    pip install eventlet cattle docker-py && \
    pip install --upgrade requests[security]==2.9.1 &&\
    apt-get remove -y --purge make libffi-dev libssl-dev gcc && apt-get autoremove -y && \
    rm -rf /tmp/Python-2.7.11

RUN curl -s -L https://downloads.hypriot.com/docker-hypriot_1.9.1-1_armhf.deb > docker-1.9.1.deb; dpkg -i docker-1.9.1.deb; apt-get install -f; cp /usr/bin/docker /usr/bin/docker-1.9; \
    curl -s -L https://downloads.hypriot.com/docker-hypriot_1.6.0-1_armhf.deb > docker-1.6.deb; dpkg -i docker-1.6.deb

RUN mkdir -p /var/lib/cattle /var/lib/rancher
COPY register.py resolve_url.py run.sh /
ENTRYPOINT ["/run.sh"]
LABEL "io.rancher.container.system"="rancher-agent"
ENV HOST_DOCKER_SOCK /var/run/docker.sock
ENV RANCHER_AGENT_IMAGE rancher/agent:v1.0.2
